'use strict';
var assert = require('assert');
var childProcess = require('child_process');
var path = require('path');
var configure = require('../utils/runtime-config');
var secret = 'test-only-configuration-value-32chars';
assert.throws(function () { configure({}); }, /SESSION_SECRET/);
assert.throws(function () { configure({SESSION_SECRET: 'short'}); }, /SESSION_SECRET/);
assert.throws(function () { configure({SESSION_SECRET: secret, NODE_TLS_REJECT_UNAUTHORIZED: '0'}); }, /TLS/);
var local = configure({SESSION_SECRET: secret});
assert.strictEqual(local.session.resave, false);
assert.strictEqual(local.session.saveUninitialized, false);
assert.strictEqual(local.session.cookie.secure, false);
assert.strictEqual(local.trackDeployment, false);
var production = configure({SESSION_SECRET: secret, NODE_ENV: 'production', TRUST_PROXY: '1', TRACK_DEPLOYMENT: '1'});
assert.strictEqual(production.session.cookie.secure, true);
assert.strictEqual(production.trustProxy, true);
assert.strictEqual(production.trackDeployment, true);
var env = Object.assign({}, process.env);
delete env.SESSION_SECRET;
var startup = childProcess.spawnSync(process.execPath, [path.join(__dirname, '../app.js')], {env: env, encoding: 'utf8'});
assert.notStrictEqual(startup.status, 0);
assert(/SESSION_SECRET/.test(startup.stderr), startup.stderr);
assert(!/Cannot find module/.test(startup.stderr), 'Validation must run before loading dependencies');
console.log('Runtime settings and real app.js fail-closed startup checks passed; no network service launched.');
